# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MjkxZWI4NDRiYWJmM2Q4MWFhMDg4MDQyYjNkNDNjNDcwMWY3YWI2ZjgwNDNiM2M0ZWFiODMzMDQ4ODM0MjIyZDkzYjAxYTU4OTVhZGZlZjdmZjQwY2U3MDJiOWY2NWQxMmUzZmRiZThjNzQ2M2ViNjVkMWNkOWQ1OTIzODhmNjM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
